Repository instana/python-sensor, pull requests merged in 2024-08, with the labels that each got.

#572 [OTel] enable instrumentation tests
  src/instana/__init__.py
  tests/conftest.py
Labels: Review & Merge, OTel_migration

#573 fix: Re-enable activation without codechange (`AUTOWRAPT_BOOTSTRAP=instana`)
  pyproject.toml
  src/instana/version.py
Labels: Review & Merge

#595 Fix: Handle instana trace suppression
  src/instana/propagators/base_propagator.py
  src/instana/tracer.py
  tests/frameworks/test_flask.py
  tests/frameworks/test_wsgi.py
Labels: Review & Merge, OTel_migration

#600 fix: Flaky test in urllib3
  tests/clients/test_urllib3.py
Labels: bug, Do not merge, OTel_migration

#602 report(currency): Fetch google cloud task results
  .tekton/.currency/docs/report.md
  .tekton/.currency/scripts/generate_report.py
Labels: Review & Merge, currency
