Repository instana/python-sensor, pull requests merged in 2024-11, with the labels that each got.

#668 Update lambda publish script
  bin/aws-lambda/build_and_publish_lambda_layer.py
Labels: enhancement, Review & Merge

#666 Fix(django): Support ASGI requests
  src/instana/instrumentation/django/middleware.py
  tests/requirements.txt
Labels: bug, enhancement, Review & Merge, OTel_migration

#673 Improve AWS Lambda Layer build script
  bin/aws-lambda/build_and_publish_lambda_layer.py
Labels: enhancement
