Repository instana/python-sensor, pull requests merged in 2024-10, with the labels that each got.

#646 Fix: Flaky tests (Part 2)
  tests/conftest.py
  tests/span/test_span.py
Labels: bug, Review & Merge

#645 Fix: Currency report generation
  .tekton/.currency/docs/report.md
  .tekton/.currency/resources/table.json
  .tekton/.currency/scripts/generate_report.py
Labels: bug, Review & Merge, currency

#640 unittest: formatted test folder structure and improved unittest coverage
  src/instana/agent/base.py
  tests/agent/test_google_cloud_run.py
  tests/agent/test_host.py
  tests/collector/helpers/test_collector_runtime.py
  tests/collector/test_base_collector.py
  tests/collector/test_gcr_collector.py
  tests/collector/test_host_collector.py
  tests/collector/test_utils.py
  tests/conftest.py
  tests/platforms/test_google_cloud_run.py
  tests/platforms/test_host.py
  tests/platforms/test_host_collector.py
  tests/propagators/test_base_propagator.py
  tests/span/test_base_span.py
  tests/span/test_event.py
  tests/span/test_readable_span.py
  tests/span/test_registered_span.py
  tests/span/test_span_sdk.py
  tests/test_sampling.py
  tests/util/test_traceutils.py
Labels: enhancement

#649 [OTel] uwsgi: uWSGI Hook Support
  src/instana/__init__.py
  src/instana/hooks/hook_uwsgi.py
Labels: OTel_migration

#650 [OTel] gunicorn: Gunicorn Hook Support
  src/instana/__init__.py
  src/instana/hooks/hook_gunicorn.py
Labels: OTel_migration

#648 fix: _log() Multiple Values for 'stacklevel'.
  src/instana/instrumentation/logging.py
  tests/clients/test_logging.py
Labels: bug, legacy_2.x

#654 chore(version): Bump version to 3.0.1
  pyproject.toml
  src/instana/version.py
Labels: Review & Merge, new_version

#655 fix: provide ASGI support with Django
  src/instana/instrumentation/django/middleware.py
Labels: bug, enhancement, Review & Merge, legacy_2.x

#657 Currency(grpcio): updated version constraints
  tests/requirements.txt
Labels: currency

#658 chore: Update README.md
  README.md
Labels: Review & Merge

#660 Adapt to logger's incoming stacklevel
  src/instana/instrumentation/logging.py
  tests/clients/test_logging.py
Labels: bug, Review & Merge

#647 Fix(currency): Run only starlette tests in `gevent_starlette` task
  .circleci/config.yml
  .tekton/pipeline.yaml
  .tekton/run_unittests.sh
  tests/conftest.py
Labels: Review & Merge, currency

#664 Fix flaky tests with inconsistent trace and span ids
  src/instana/util/ids.py
  tests_aws/01_lambda/test_lambda.py
Labels: bug

#663 chore: Add GitHub CODEOWNERS file.
  .github/CODEOWNERS
Labels: Review & Merge

#665 fix: post branch rename changes
  .github/workflows/pr_commits_signed_off.yml
  .github/workflows/sonarqube.yml
  .tekton/.currency/currency-pipelinerun.yaml
  .tekton/.currency/currency-scheduled-eventlistener.yaml
  .tekton/README.md
  .tekton/github-pr-pipeline.yaml.part
  .tekton/scheduled-eventlistener.yaml
  README.md
  RELEASE.md
Labels: Review & Merge
