Repository instana/python-sensor, pull requests merged in 2024-09, with the labels that each got.

#605 fix: Capture the correct log caller
  src/instana/instrumentation/logging.py
  tests/clients/test_logging.py
Labels: bug, Review & Merge

#606 Fix OTel logging tests
  tests/clients/test_logging.py
Labels: Review & Merge, OTel_migration

#620 chore(version): Bump version to 2.5.3
  src/instana/version.py
Labels: enhancement, Review & Merge

#622 refactor: Remove TestAgent from the production code.
  .circleci/config.yml
  .tekton/run_unittests.sh
  src/instana/agent/host.py
  src/instana/agent/test.py
  src/instana/collector/aws_fargate.py
  src/instana/collector/base.py
  src/instana/fsm.py
  src/instana/recorder.py
  src/instana/singletons.py
  tests/__init__.py
  tests/agent/test_host.py
  tests/apps/grpc_server/stan_server.py
  tests/conftest.py
  tests/platforms/conftest.py
  tests/test_tracer.py
  tests/test_tracer_provider.py
Labels: enhancement, Review & Merge, OTel_migration

#624 added cassandra to instrumentation imports
  src/instana/__init__.py
Labels: Review & Merge

#630 fix: Remove an unsupported top level span attribute.
  src/instana/span/base_span.py
  tests/frameworks/test_flask.py
  tests/span/test_base_span.py
Labels: Review & Merge, OTel_migration

#632 tornado_server: skip flaky tests
  tests/frameworks/test_tornado_server.py
Labels: Review & Merge, OTel_migration

#636 [OTel] Fix: test_span caplog setup
  tests/span/test_span.py
Labels: bug, OTel_migration
