Repository instana/python-sensor, pull requests merged in 2024-07, with the labels that each got.

#548 report(currency): update support policy
  .tekton/.currency/resources/table.json
Labels: currency

#555 report(currency): Update support policy.
  .tekton/.currency/currency-tasks.yaml
  .tekton/.currency/resources/table.json
Labels: Review & Merge

#564 fix: TracerProvider.get_tracer() after API update.
  pyproject.toml
  src/instana/tracer.py
Labels: OTel_migration

#566 Added constraint for setuptools Python module
  tests/requirements-310.txt
  tests/requirements-312.txt
  tests/requirements-313.txt
  tests/requirements.txt
Labels: bug, Review & Merge

#567 fix: log message >WARN not showing up in the UI
  src/instana/span/registered_span.py
  tests/clients/test_logging.py
  tests/test_span_registered.py
Labels: Review & Merge, OTel_migration
