Repository instana/python-sensor, pull requests merged in 2025-05, with the labels that each got.

#726 chore(docker-compose): remove top-level `version` attribute
  docker-compose.yml
Labels: enhancement, Review & Merge

#721 fix: Kafka context propagation
  src/instana/instrumentation/kafka/confluent_kafka_python.py
  src/instana/instrumentation/kafka/kafka_python.py
  src/instana/propagators/base_propagator.py
  src/instana/propagators/kafka_propagator.py
  src/instana/tracer.py
  tests/clients/kafka/test_confluent_kafka.py
  tests/clients/kafka/test_kafka_python.py
Labels: bug, wip

#732 fix: Function type has been updated
  src/instana/instrumentation/aioamqp.py
Labels: bug

#733 chore (tests): Reusing the requirements-minimal.txt file.
  tests/requirements-cassandra.txt
  tests/requirements-couchbase.txt
  tests/requirements-gevent-starlette.txt
  tests/requirements-kafka.txt
  tests/requirements-pre314.txt
  tests/requirements.txt
Labels: enhancement, dependencies, Review & Merge

#735 fix (ci): Fix Python 3.14.0 container image build.
  Dockerfile-py3140
Labels: Review & Merge, currency, ci/cd

#740 chore(version): Bump version to 3.4.1
  src/instana/version.py
Labels: Review & Merge, new_version
