Repository instana/python-sensor, pull requests merged in 2025-06, with the labels that each got.

#742 ci: Add support to test Python 3.14.0b2.
  .tekton/pipeline.yaml
  .tekton/python-tracer-prepuller.yaml
  Dockerfile-py3140
Labels: Review & Merge, currency, ci/cd

#749 Fix: CI errors with sanic
  tests/conftest.py
  tests/requirements-pre314.txt
  tests/requirements.txt
Labels: bug, Review & Merge, ci/cd

#751 kafka: improve flaky unittests
  tests/clients/kafka/test_confluent_kafka.py
Labels: unittest
