Repository instana/python-sensor, pull requests merged in 2025-01, with the labels that each got.

#679 fix(sanic): remove 3.8 support for latest versions
  tests/requirements.txt
Labels: bug

#680 ci: Add support for latest runtime version 3.14.0a3
  .circleci/config.yml
  .tekton/pipeline.yaml
  .tekton/python-tracer-prepuller.yaml
Labels: currency

#683 chore(version): Bump version to 3.2.0
  src/instana/version.py
Labels: Review & Merge, new_version

#684 fix(ci): Condition to start the package building.
  .github/workflows/pkg_release.yml
Labels: bug, Review & Merge

#686 Fix: Add new AWS region `ap-southeast-7` to publish
  bin/aws-lambda/build_and_publish_lambda_layer.py
Labels: enhancement, Review & Merge

#687 ci: Add support to test Python 3.14.0a4.
  .circleci/config.yml
  .tekton/pipeline.yaml
  .tekton/python-tracer-prepuller.yaml
Labels: currency

#689 fix: capture headers
  src/instana/util/traceutils.py
Labels: bug, Review & Merge

#690 fix: use the correct image for 3.14.0a4
  .tekton/pipeline.yaml
  .tekton/python-tracer-prepuller.yaml
Labels: bug, Review & Merge, currency
