Repository instana/python-sensor, pull requests merged in 2025-07, with the labels that each got.

#758 Add new AWS region to publish script.
  bin/aws-lambda/build_and_publish_lambda_layer.py
Labels: enhancement, Review & Merge, currency, ci/cd

#765 chore(version): Bump version to 3.6.0
  src/instana/version.py
Labels: Review & Merge, new_version, ci/cd

#766 Remove six package and its usage since Python 2 is no longer supported
  pyproject.toml
  src/instana/span/base_span.py
  tests/clients/test_google-cloud-pubsub.py
  tests/clients/test_google-cloud-storage.py
Labels: enhancement, fix, refactor
