Repository instana/python-sensor, pull requests merged in 2025-09, with the labels that each got.

#788 ci: enable sonar scanning and report results to sonacloud.io
  .circleci/config.yml
  sonar-project.properties
Labels: Review & Merge, ci/cd

#796 fix: fixed reading suppression header from message's headers
  src/instana/instrumentation/kafka/kafka_python.py
Labels: fix

#801 (chore): AWS Lambda layer publishing script updates.
  bin/aws-lambda/build_and_publish_lambda_layer.py
Labels: currency, ci/cd, chore
