Repository instana/python-sensor, pull requests merged in 2025-02, with the labels that each got.

#692 chore(version): Bump version to 3.3.0
  src/instana/version.py
Labels: Review & Merge, new_version

#694 ci: Add support to test Python 3.12.9 and 3.13.2.
  .tekton/pipeline.yaml
  .tekton/python-tracer-prepuller.yaml
Labels: Review & Merge, currency

#695 fix: remove unsupported span attribute
  src/instana/instrumentation/asgi.py
  src/instana/instrumentation/pep0249.py
  src/instana/instrumentation/pyramid.py
  src/instana/instrumentation/sanic_inst.py
  src/instana/span/registered_span.py
  tests/clients/test_pep0249.py
  tests/span/test_registered_span.py
Labels: bug

#697 ci: Add support to test Python 3.14.0a5.
  .circleci/config.yml
  .tekton/pipeline.yaml
  .tekton/python-tracer-prepuller.yaml
Labels: Review & Merge, currency

#698 chore: Ignore uv.lock file on Git.
  .gitignore
Labels: Review & Merge
